// <auto-generated />
using System;
using HikingTrails.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HikingTrails.Migrations
{
    [DbContext(typeof(HikingTrailsContext))]
    [Migration("20210421010229_20210420")]
    partial class _20210420
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HikingTrails.Models.Hike", b =>
                {
                    b.Property<int>("HikeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrailId")
                        .HasColumnType("int");

                    b.Property<string>("Trailname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HikeId");

                    b.ToTable("Hike");
                });

            modelBuilder.Entity("HikingTrails.Models.Trail", b =>
                {
                    b.Property<int>("TrailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrailName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrailId");

                    b.ToTable("Trail");

                    b.HasData(
                        new
                        {
                            TrailId = 1,
                            Location = "Milford, OH",
                            TrailName = "Rowe Woods"
                        },
                        new
                        {
                            TrailId = 2,
                            Location = "Goshen, OH",
                            TrailName = "Long Branch Farm"
                        },
                        new
                        {
                            TrailId = 3,
                            Location = "Logan, OH",
                            TrailName = "Whispering Cave"
                        });
                });

            modelBuilder.Entity("HikingTrails.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Age = 54,
                            Bio = "I'm a non-traditional student in the software development track. I have about 10 classes to go for my Bachelor's Degree. I got my Associate's Degree in Computer Engineering Technology in 1994 from Cincinnati Technical College.",
                            FirstName = "Anthony",
                            LastName = "Morgan"
                        },
                        new
                        {
                            UserId = 2,
                            Age = 20,
                            Bio = "Hello, my name is Wes and I'm a 3rd year IT student in the software and cyber tracks. I'm also in the IT accelerated program for my MSIT, and I play Trombone in the Bearcat Bands.",
                            FirstName = "Wesley",
                            LastName = "Reed"
                        },
                        new
                        {
                            UserId = 3,
                            Age = 23,
                            Bio = "Hello, my name is Christian and I'm a 3rd year IT student in the software development track. I don't go hiking regularly, but the few times I have gone were pretty fun.",
                            FirstName = "Christian",
                            LastName = "Rosario"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
