// <auto-generated />
using HikingTrails.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HikingTrails.Migrations
{
    [DbContext(typeof(HikingTrailsContext))]
    [Migration("20210419225941_HikeRelationship")]
    partial class HikeRelationship
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HikingTrails.Models.Hike", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("TrailId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "TrailId");

                    b.HasIndex("TrailId");

                    b.ToTable("Hike");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            TrailId = 1
                        },
                        new
                        {
                            UserId = 2,
                            TrailId = 1
                        },
                        new
                        {
                            UserId = 3,
                            TrailId = 2
                        },
                        new
                        {
                            UserId = 4,
                            TrailId = 2
                        },
                        new
                        {
                            UserId = 5,
                            TrailId = 3
                        });
                });

            modelBuilder.Entity("HikingTrails.Models.Trail", b =>
                {
                    b.Property<int>("TrailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrailName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrailId");

                    b.ToTable("Trail");

                    b.HasData(
                        new
                        {
                            TrailId = 1,
                            Location = "Milford, OH",
                            TrailName = "Rowe Woods"
                        },
                        new
                        {
                            TrailId = 2,
                            Location = "Goshen, OH",
                            TrailName = "Long Branch Farm"
                        },
                        new
                        {
                            TrailId = 3,
                            Location = "Logan, OH",
                            TrailName = "Whispering Cave"
                        });
                });

            modelBuilder.Entity("HikingTrails.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Age = 54,
                            Bio = "I'm a non-traditional student in the software development track. I have about 10 classes to go for my Bachelor's Degree. I got my Associate's Degree in Computer Engineering Technology in 1994 from Cincinnati Technical College.",
                            FirstName = "Anthony",
                            LastName = "Morgan"
                        },
                        new
                        {
                            UserId = 2,
                            Age = 20,
                            Bio = "Hello, my name is Wes and I'm a 3rd year IT student in the software and cyber tracks. I'm also in the IT accelerated program for my MSIT, and I play Trombone in the Bearcat Bands.",
                            FirstName = "Wesley",
                            LastName = "Reed"
                        },
                        new
                        {
                            UserId = 3,
                            Age = 23,
                            Bio = "Hello, my name is Christian and I'm a 3rd year IT student in the software development track. I don't go hiking regularly, but the few times I have gone were pretty fun.",
                            FirstName = "Christian",
                            LastName = "Rosario"
                        },
                        new
                        {
                            UserId = 4,
                            Age = 21,
                            Bio = "I'm a fourth year IT student with tracks in software development as well as game design and simulation.",
                            FirstName = "David",
                            LastName = "Stober"
                        },
                        new
                        {
                            UserId = 5,
                            Age = 21,
                            Bio = "Hello, my name is Robby and I'm a 3rd year IT student in the software development track, aswell as an ACCEND student, doing my MBA. I love hiking, camping and the outdoors in general, my favorite hiking spot around here is Glen Helen Trail up in Yellow Springs. My passion in life is Music and i hope to one day open a music school and create interactive software to both help people learn to play music and to help composers get out of creative block.",
                            FirstName = "Robby",
                            LastName = "Hoover"
                        });
                });

            modelBuilder.Entity("HikingTrails.Models.Hike", b =>
                {
                    b.HasOne("HikingTrails.Models.Trail", "Trail")
                        .WithMany("Hikes")
                        .HasForeignKey("TrailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HikingTrails.Models.User", "User")
                        .WithMany("Hikes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trail");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HikingTrails.Models.Trail", b =>
                {
                    b.Navigation("Hikes");
                });

            modelBuilder.Entity("HikingTrails.Models.User", b =>
                {
                    b.Navigation("Hikes");
                });
#pragma warning restore 612, 618
        }
    }
}
